### ISSUE TITLE
Resin Todo

### ISSUE THREAD

**Issue by abkfenris** [abkfenris/gage-beaglebone#16]
- [ ] Power cycling
  - [x] [shutdown via API](https://docs.resin.io/runtime/supervisor-api/#post-v1-reboot)
  - [x] env startup reasons
  - [x] env restart timeouts
  - [x] env variable to configure if power cycling should run
  - [x] env variable for boot timeout
  - [ ] toggle charge timeout in AVR register (requires some idea of current and voltage) - timeout on new capes is 10 hours rather than 3
- [x] cell modem #19 
  - [x] write config if it doesn't exist
  - [x] enable kernel module and enumerate device
- [x] CSV append to file on microsd
- [x] Clears out CSV old log files on microsd
- [x] mount microsd card
  - Mounting volumes [1](https://docs.resin.io/runtime/runtime/#mounting-external-storage-media) [2](https://forums.resin.io/t/mounting-usb-storage-stick/767/3)
- [ ] rtc
  - [x] read from rtc on boot
  - [ ] if rtc invalid wait for ntpdate
    - [x] write to rtc
- [x] halt before power gets too low (3.3v ? LiPO really don't like to get into the 2s) 
- [ ] Include function [timeouts](http://stackoverflow.com/a/2282656/3658919)
- [ ] Document environment variables
- [x] [Toggle light on PowerCape](https://github.com/AndiceLabs/PowerCape/blob/master/avr/registers.h) when it has an 
  - [x] internet connection
  - [x] SD card 
- [x] offline shutdown and device management #21 
- [x] Rotating Log on SD
- [x] Log format for SD log
- [x] Web and SD logging levels via env variables
- [x] logging if SD not avaliable
- [x] stop for file on microsd
- [x] error but continue if microsd inaccessable
- [ ] Sample for a fixed large amount, or only check every 10 or so values
- [x] use [importlib](http://stackoverflow.com/a/10675081/3658919) to import the cell module so it can be chosen by env variable
- [ ] Catch sigterm?
- [x] log formating to files
  - [x] time
  - [x] level
- [x] Sentry logging. Should be able to set site `client = raven.Client(DSN, site='bull-branch')`
