### ISSUE TITLE
Todo for Bull Branch Prototype

### ISSUE THREAD

**Issue by abkfenris** [abkfenris/gage-beaglebone#8]
- [ ] Include restart time in config
- [ ] Update restart time each run
- [ ] Check current datetime isn't earlier than last recorded datetime
  - [ ] If off: start cell, get current time, write to RTC, get sample
- [ ] Get cell working
- [ ] Make mount for solar panel (a couple of big hinges and bend them a bit?)
- [ ] More explicit error checking
- [ ] Organize cell classes into vendor directories and load via config
- [ ] Update startup options
- [ ] Poweroff timeout both at beginning of cycle and during shutdown
